name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Display runner information
        run: |
          echo "Running on GitHub-hosted runner"
          hostname
          uname -a
          pwd
          ls -la
          cat /etc/os-release
          sudo apt update
          sudo apt install nginx -y
          sudo ufw allow 'Nginx HTTP'
          sudo systemctl status nginx
          
